### ISSUE TITLE
Can't access binaries

### ISSUE THREAD

**Issue by JRomeoSalazar** [h4cc/wkhtmltopdf-amd64#1]
Hi, I've tried to use your bundle but I haven't been able. It throws me an error:

```
Warning: Unknown: A session is active. You cannot change the session module's ini settings at this time in Unknown on line 0
```

Do you know why?

This is knp snappy bundle config:

``` yaml
knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../bin/wkhtmltopdf-amd64
        options:    []
```

How should I use your bundle?

Thanks!
